### ISSUE TITLE
[Suggestion] Block to contain Radiation

### ISSUE THREAD

**Issue by LokeYourC3PH** [tomdodd4598/NuclearCraft#503]
So this is only a small suggestion/request I would like to make for the mod. 

I REALLY love the Radiation aspect, it finally adds some things to worry for in Minecraft that cannot be easily solved but using a single item or block or the likes. However, people constantly ask me on my server if there is a way to get rid of Radiation or contain it, however I can only tell them to use Radiation Scrubbers, which in themselves are cool and get the job done, are however kind of the only way to contain it. What would be cool, is adding either a new type of block OR making it so that Lead Blocks can somewhat contain the Radiation. Example:

RTG's naturally spread a lot of Radiation, especially Californium RTG's (and so do some other blocks and Reactors). It would be cool to be able to make a room of like 5 blocks (or more or less, maybe the thicker the better it contains the Radiation, dunno) thick facades that can contain some (hopefully configurable) amount of Radiation. It would be even cooler if there were necessities like having to make an airlock or double door system in order to have a room in-between where you can decontaminate yourself with a shower or the likes so that it is truly possible to work on Nuclear Reactors or the likes in almost separate environments where you have to be really careful with Radiation.

That would be all :D

**Comment by turbodiesel4598** [comment]
Again, this is actually a pretty tricky one :P

We've been discussing mechanics like this in the NC discord server for some time now. The reason this is tricky is because of the inherently chunk-based nature of the radiation mechanics, and so on top of the problem of efficient ray-tracing and/or container-detection, this becomes rather nasty.

I believe there is possibly work being done on an NC addon which will add mechanics a bit like this, at least in some basic form :)

**Comment by C4PTRAMPAGE** [comment]
> Again, this is actually a pretty tricky one :P

Hey i know, what if you added some sort of forcefield generator? where the size of the field is adjusted in chunks and say tier 1 of the machine can just block half of the rads from spreading to neighboring chunks tier 2 can block all rads and tier 3... can block explosions and endermen picking up blocks maybe? idk. although keeping in line with NC's way of doing things instead of tiered machines have tiered upgrade items or could even make it a multiblock structure!

**Comment by C4PTRAMPAGE** [comment]
also tiers 4 could stop rads from spreading into the shield, and act as a barrier to mobs and players that aren't on a whitelist!

**Comment by turbodiesel4598** [comment]
@C4PTRAMPAGE It's not really that which is the problem - scrubbers can basically already do that, and extra features such as shields and so forth are probs not really worth adding when there is already a similar feature and so much other stuff for me to get round to implementing. The discussion is around inter-chunk shielding, which can only be solved by a ray tracing/casting system of some sort.

**Comment by BlueVal** [comment]
Deep Resonance has a bit of a shielding like this: https://www.curseforge.com/minecraft/mc-mods/deep-resonance

Not sure what it would use but it may help potentially?

**Comment by Enginecrafter77** [comment]
I kniw this is going to sound a little bit overcomplicated, but I may have an idea how that could work without raytracing occuring each tick (which would be a huge performance eater).

As far as I am aware, nuclearcraft has already extensive framework for multiblock structures involving "unchecked blocks", i.e. blocks that are not chcecked by the algorithm. This includes pipes from other mods and so on. Well, this could be theoretically used to build a sort of containment structure around the reactor. This structure would, when formed, disable the radiation source of the reactor and any contained blocks whatsoever. Instead, it would itself emmit a negligible radiation (i.e. the radiation that slipped through / configurable) and apply full dose to players/entities located inside the containment structure. This approach, despite being a little bit overcomplicated, would eliminate the need of raytracing the ionizing radiation, as well as the need to place numerous slow-acting scrubbers.

**Comment by Sabrewulf** [comment]
Why not the own reactor walls is the containment structure?
Just make it cheaper for players make bigger and add a block for use next walls for reduce radiation.
Would be nice a "water block " acting like air to work as irradiated air inside reactor, so if reactor wall break it will spread to be used by modder for a lot of especial effects.

**Comment by Enginecrafter77** [comment]
Yeah, it would be acceptable but it wouldn't make much sense. In real world, the pressure vessel (think NC reactor) is emmiting huge amounts of radiation (less than the core itself though), and so it needs additional containment structure. Also, this approach I mentioned above would not only work for reactors, but for any radiation emmiting block, even those from potential implementing mods (mods that use NC API to provide radiation).

The approach I mentioned was taken from pragamtic point of view, i.e. what's really doable without much coding or performance impact on the game itself.

**Comment by Solverbolt** [comment]
Is there anything new with this? a Way to build a shielded room to prevent radiation leakage into other chunks. Because a friend of mine setup a simple uranium rtg and suddenly radiation is all over the place
