### ISSUE TITLE
Cherenkov radiation

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [tomdodd4598/NuclearCraft#548]
please make reactor cores surrounded by water glow blue (also maybe make filling a reactor with water source blocks an early game way to cool them?) i mean it wouldn't add anything other than shiny to the mod but isn't that enough?

**Comment by turbodiesel4598** [comment]
This is already on the to do list, but just far down as there's lots of other stuff to get done and I am also not an expert on rendering effects.

**Comment by C4PTRAMPAGE** [comment]
good to hear, thanks.

**Comment by AquaticFish** [comment]
Wowzies, you might have issues with this, Tom. If you're talking about an actual lighting glow, you are going to have compatibility issues with Optifine, this has been done in the past but Optifine's closed source prevents people from probably implementing compatibility features.

**Comment by ben-mkiv** [comment]
You can compile against Optifine and disable Shaders while rendering your own custom Shader.

It's just that people didnt bother with it and just blamed Optifine for being closed source, if people did that in the first place with Minecraft we wouldn't have so many mods nowadays...

**Comment by tomdodd4598** [comment]
Unfortunately, although initially on my long-term to-do list, I do not think I am going to have the time at this point to look into how to render effects like this - apologies!
