### ISSUE TITLE
[Suggestion] NuclearCraft Lite for Tinkers

### ISSUE THREAD

**Issue by tyberiuscodes** [tomdodd4598/NuclearCraft#605]
Hi there! First of all, I wanted to say that I really enjoyed messing with this mod in Sky Factory 4, especially when it came to its integration with Tinkers Construct and Constructs Armory. Now I'm trying to put together a personal modpack for myself and my partner, and of course we want to include Tinkers. However, we're trying to go for something different and keep the pack low-tech, but I realized that my favorite Tinkers materials (Hard Carbon, Thorium, and several others) are from NuclearCraft.

My suggestion/request is to possibly make a "Lite" version of NuclearCraft for such instances. It would likely only consist of the alloys and ores added by NC (including their world gen) and then the Tinkers integration aspects. Melting ores, making ingots, and creating alloys could be handled by Tinkers smeltery, rather than the more advanced machines in NC.

I apologize if this request sounds rude at all. I know that NC's focus is on the more high-tech aspects (again, I very much enjoyed it in SF4!), and I don't mean to belittle it in any way by essentially asking for a completely stripped down version. The truth is I'm making this somewhat silly request _because_ I enjoy the complexity NC helps add to Tinkers through its additional materials and alloys (the alloys being one of my favorite parts) and I felt like its implementation was extremely thoughtful and balanced. I sincerely tried messing with making something like this myself from the source, but I have no idea what I'm doing when it comes to Java, unfortunately.

**Comment by tekker2234** [comment]
if you know your way around crafttweaker and have a lot of time you can probably just disable everything exept the ores/alloys

**Comment by turbodiesel4598** [comment]
@trashxking Sorry for responding to this so late! It would probably take me a little while to extract just the Tinkers' pieces from the mod as a whole and build that separately, and unfortunately I've barely got the time to do much more than work on updating the mod, but for 1.14.4 I'll definitely consider modularising the mod so that people can pick the bits they want. Typically these sorts of big decisions are made via discussion and polls in our [Discord server](https://discord.gg/KCPYgWw) ;)

**Comment by trashxking** [comment]
@turbodiesel4598 Thank you for the consideration!

**Comment by ChromaPIE** [comment]
As it is labelled as a long term plan, IMO it is strongly recommended to use CraftTweaker and ContentTweaker to make a rough system to satisfy your idea a bit. NuclearCraft and TiC both have perfect integrations for CoT and CrT! Before Lite comes true you can have a try.

**Comment by tomdodd4598** [comment]
Apologies for the late reply after many years, but unfortunately I do not think I will have time to put something like this together for 1.12.2. As I mentioned previously, however, this sort of thing should be easier in future versions as long as I modularise the mod!
