### ISSUE TITLE
(NCO) [Suggestion] Endgame machines

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [tomdodd4598/NuclearCraft#642]
A fusion reactor that uses direct energy conversion and with machines that run on reactor plasma and power for example a furnace that uses electricity and reactor plasma to double ingot output from ores and can melt through a stack of ores in about a second, or maybe even a replicator powered by electricity and reactor plasma to break down blocks, items and liquids into matter plasma and use that to make other (whitelisted) blocks, items and liquids, so basically a less overpowered version of matter overdrive.

**Comment by turbodiesel4598** [comment]
I probably won't add plasma-fuelled machines, but I may add replicator-like tech in the far future. Right now there's a lot of other stuff to get done though :P

**Comment by C4PTRAMPAGE** [comment]
i understand if you dont think its a good idea to have machines that run at least in part off of fusion plasma but my reasoning for that is (assuming only the final reactor has plasma outlet ports) it locks the endgame machines to the endgame reactor so you cant just build a replicator by itself, you need the support hardware.

**Comment by turbodiesel4598** [comment]
The 'endgame' machines planned for NC will likely use even more advanced technology, mainly synchrotron radiation from a particle accelerator :)

**Comment by tomdodd4598** [comment]
With QMD adding late-game particle physics multiblocks, and the recent addition of custom CraftTweaker processors, I realistically probably won't be adding much late-game tech to NCO at this point, as I want to just add the features that I promised in the Discord server before moving to later versions of MC.
