### ISSUE TITLE
[Suggestion] Maybe Suggestion After Overhaul

### ISSUE THREAD

**Issue by PulseBeat02** [tomdodd4598/NuclearCraft#677]
Hi, I am aware of the overhaul that is taking place currently, but I just really wanted to throw out an idea. I was thinking that because nuclear reactors also create heat, NuclearCraft machines like the Manufactory, etc, should also produce heat. It could be set up like the higher the heat, the less efficient the machine will run. There would be a new upgrade slot with an item called "Cooling Upgrade" which could be used to decrease the cooling rate of the machine linearly. Methods to cool the machine might include using water, or other possible new liquids that are designated for liquid cooling. By the way, this mod is great. I love it. Good luck during the overhaul!

**Comment by salomj** [comment]
That could be how overclocking the machine works. Just add a ton of radiators to it.

**Comment by ShootinIdiotTech** [comment]
> That could be how overclocking the machine works. Just add a ton of radiators to it.

He mention about "Cooling Upgrade" - and it's not that bad idea cause you can put a limit of usage on certain machines and one "Cooling Upgrade" could reduce heat amount by 5% and you can put for example max. 5 of them to machine.
