### ISSUE TITLE
[Suggestion] FBR - Fast Breeder Reactor

### ISSUE THREAD

**Issue by ShootinIdiotTech** [tomdodd4598/NuclearCraft#699]
I have an suggestion to implement Fast Breeder Reactor in to NC, it could be useful to obtain same or larger amounts of energy without need to refuel it too often comparing to normal reactor and to make HE fuels, well there's link to wiki how FBR's works: https://en.wikipedia.org/wiki/Breeder_reactor

**Comment by turbodiesel4598** [comment]
The concept of a breeder reactor is inherently mixed into NC's fuel reprocessing tree, but fast reactors have been considered and may be added in the future :)

**Comment by tomdodd4598** [comment]
At this point, I realistically probably won't be adding more reactors to NCO past the ones I promised in the Discord server. After I move to later versions of MC, I may add other types of reactors, but it very much depends on the time I have available.
