### ISSUE TITLE
Potentially change the slot config behavior

### ISSUE THREAD

**Issue by krallendertoten** [tomdodd4598/NuclearCraft#743]
After seeing people complain about the way the machine slot configuration behavior works, specifically in regards to voiding inputs, it might be nice to change the way these settings are applied. Perhaps using the menu to set up the config only visually for the player and having an "apply" button would be useful to make it a bit more beginner-friendly

**Comment by tomdodd4598** [comment]
In the next version of NCO, the voiding will only begin happen when the player actually leaves the GUI :)
